device: cuda
dataloader:
  batch_size: 4
  num_workers: 2
  shuffle: True

stage1:
  loss: mse
  epochs: 50
  limit_iters: null
  netG:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0  

stage2:
  loss: bce
  epochs: 50
  limit_iters: null
  netG:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.001
  netGD:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.001
  netLD:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.001
