device: cuda
dataloader:
  batch_size: 4
  num_workers: 2
  shuffle: True

stage1:
  loss: mse
  epochs: 10
  limit_iters: 200
  netG:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0  

stage2:
  discriminator_loss: bce
  generator_loss: mse
  epochs: 60
  limit_iters: 200
  netG:
    train_every: 2
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
    mse_weight: 1
    local_weight: 100
    global_weight: 100
  netGD:
    train_every: 1
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
  netLD:
    train_every: 1
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
