device: cuda
dataloader:
  batch_size: 4
  num_workers: 2
  shuffle: True
stage1:
  loss: mse
  optimizer: adamw
  epochs: 10
  lr: 0.001
  weight_decay: 0.001  
stage2:
  loss: bce
  loss_aggregation: sum
  optimizer: adamw
  epochs: 10
  lr: 0.001
  weight_decay: 0.001
