device: cuda
dataloader:
  batch_size: 3
  num_workers: 2
  shuffle: True

stage1:
  loss: mse
  epochs: 12
  limit_iters: null
  netG:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0  

stage2:
  loss: bce
  epochs: 20
  limit_iters: null
  netG:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
  netGD:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
  netLD:
    optimizer: adam
    lr: 0.0001
    weight_decay: 0.0
